plugin.version=${project.version}
server.variant=${server.variant}
minecraft.api.version=${minecraft.api.version}
paper.min=${paper.supported.min}
paper.max=${paper.supported.max}
folia.min=${folia.supported.min}
folia.max=${folia.supported.max}
folia.supported=${folia.supported}
